### ISSUE TITLE
Problems with the Pork-Chop Test Program

### ISSUE THREAD

**Issue by OrbitalMechanic** [jacobwilliams/Fortran-Astrodynamics-Toolkit#1]
I was able to build pork_chop.f. However when I run pork_chop.py I get the following messages:

``` python
/Users/user/anaconda/lib/python2.7/site-packages/matplotlib/text.py:52: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if rotation in ('horizontal', None):
/Users/user/anaconda/lib/python2.7/site-packages/matplotlib/text.py:54: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif rotation == 'vertical':
```

Any suggestion as to how to correct this?

**Comment by jacobwilliams** [comment]
Is the `pork_chop.png` file generated? I get the same warnings the first time I run the `pork_chop.py` script, but the file is still generated. I think it is some kind of matplotlib bug.

**Comment by OrbitalMechanic** [comment]
When I saw first cloned the toolkit via GitHub I saw the pork_chop.png 
file in the pork_chop sub-directory and thought it was a sort of "truth" 
version of the image that the code should generated. Now when I check 
the file information it is indeed the image I was expecting. Thanks for 
clearing this matter up.

BTW, just what do these warnings mean?

**Comment by jacobwilliams** [comment]
I don't know. There is a post [here](http://stackoverflow.com/questions/30278393/python-unicode-warning-unicode-equal-comparison-failed-to-convert-both-argument) with the same issue, and a couple other posts also.

**Comment by OrbitalMechanic** [comment]
Thanks for the link. I believe I understand the message a little better now.
