### ISSUE TITLE
Standish Method Accuracy Check

### ISSUE THREAD

**Issue by CumuloEpsilon** [jacobwilliams/Fortran-Astrodynamics-Toolkit#12]
You currently use the DExxx (ie DE430) ephemeris in the JAT. It may be possible in future you will find it useful to incorporate an approximation method such as the Standish approach as in my Standish_Module (https://github.com/CumuloEpsilon/Standish-Ephemeris). The comparable SOFA iau-plan94  licensing is ... ah, blek, unfortunate, but Standish has a BSD! Be advised that I have no objection, even if you must recode to the horror known as oop. (just not too many levels of abstraction please, sigh). Certainly I think that would be a proper addition to the fat. Happy to cooperate, just say so.

As you are following I note I found a programming error in Standish affecting results outside the 1800-2050 AD range, a one character change detailed as Bug 20180219-1. Also I did an accuracy check against DE430 which might interest you, in the project as standish_accuracy.pdf. Enjoy.
-CumuloEpsilon

**Comment by jacobwilliams** [comment]
Thanks!  I’ll take a look.
