### ISSUE TITLE
get_third_party SED

### ISSUE THREAD

**Issue by CumuloEpsilon** [jacobwilliams/Fortran-Astrodynamics-Toolkit#14]
Jacob,

Line 13 of your get_third_party.sh contains the script line
sed -i '_original' '/^C.*PARAMETER ( NRECL = 4 )/s/^C//' asc2eph.f

the "sed -i " throws an error on my debian linux (Raspbian), indicating the -i option is not linux compatible. It appears to be a Mac variant of insert-in-place. By consequence the third party script fails and the ephemeris does not build. 
Unfortunately I am not skilled enough to advance a fix for you. I found the following similar discussion/fix which indicates a Mac/linux incompatibility on this and suggests a fix. 

https://github.com/despark/kohana/commit/656e1f75e41520d678af8c0001b09e1d9a774527#commitcomment-5632757

Hope this helps. If you suggest an idea here I can test it for you. Best.
-Cumulo

**Comment by jacobwilliams** [comment]
Yes, I wrote that script on a Mac. I'll try to work out a fix on a linux system when I get a chance.

**Comment by CumuloEpsilon** [comment]
@jacob
OK. I can give it some thought also. For folks who need immediate help an alternative of manually editing the NRECL line in the  asc2eph.f file  then executing the other commands works (thats what I did) . HOWEVER, I might also point out that the resulting file and the full binary 405 ephemeris downloaded from JPL have identical md5 checksums (are byte identical) to my gfortran generated file and I have likewise tested the file using gfortran on both windows and linux systems, and it works fine. Maybe JPL uses gfortran! ;) Might not be same result for other fortran flavors, however. For gfortran though, no probs. Just mentioning it.

Meanwhile we can leave this issue open for present to see if a fix presents itself, or someone else has an idea.
Regards, Cumulo
