### ISSUE TITLE
orbital_mechanics_module  true anomaly

### ISSUE THREAD

**Issue by CumuloEpsilon** [jacobwilliams/Fortran-Astrodynamics-Toolkit#15]
Jacob,

Appreciate the orbital mechanics routines, helpful
 It is my understanding that by convention the true anomaly (tru) is in the range 0 to 2pi.  Your use of wrap_angle places the range of tru in the range -pi to pi. The true anomaly of Mars on 2463114 is returned by rv_to_orbital_elements as -45 deg, rather than 315 deg for example. I'm no fanatic about such things where, as here,  they make no computational difference, but we (our brains) do kinda get used to seeing things a particular way, like velocities in kps, it speeds our analysis. I note that NASA reports the element TA in the range 0 to 2pi.

Would you look at your use of the wrap_angle in this context, particularly for tru, and see if it is as you intended?

-Cumulo

**Comment by jacobwilliams** [comment]
Hmmm, I tend to prefer the [-180,180] convention for some reason!

**Comment by CumuloEpsilon** [comment]
@jacobwilliams 
OK. You are the author, entitled to your way. I can convert it if I need to . I Still think 0-2pi is correct for M, E, and tru, I have no idea where +-pi is used, but I never argue with a nasa trained geek.  Anyway,  I figure that's probably just how you mac people must roll.
(my wife is a mac, she has a mbpro and a mac mini with thunderbolt disp, both i7's with extra mem - she does all the heavy computing on them - web surfing and email- alas  they cost so much money I'm left to do the astronomy and quantum mechanics and other such stuff on a $30 raspberry pi. Life just isn't fair, never was.  )
I'll leave this open for a few days to allow other comments. 
Best, Cumulo
