### ISSUE TITLE
error building under FPM 

### ISSUE THREAD

**Issue by n7275** [jacobwilliams/Fortran-Astrodynamics-Toolkit#26]
Hopefully this is the best place to post this. I'm trying to build using FPM on a Raspbery pi 3.

> + gfortran -c ./src/eispack_module.f90  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array->temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o >build/gfortran_2A42023B310FA28D/fortran-astrodynamics-toolkit/src_eispack_module.f90.o
>./src/eispack_module.f90:1549:42:
>
>             write(*,'(F16.6,F16.6)') v(j)%re, v(j)%im
>                                          1
>Error: Unexpected ‘%’ for nonderived-type variable ‘v’ at (1)
>compilation terminated due to -fmax-errors=1.
><ERROR> Compilation failed for object " src_eispack_module.f90.o "
><ERROR>stopping due to failed compilation
>STOP 1

**Comment by jacobwilliams** [comment]
This `%re` and `%im` are newer Fortran features (maybe Fortran 2008?) So you must be using an older compiler.

**Comment by n7275** [comment]
> This `%re` and `%im` are newer Fortran features (maybe Fortran 2008?) So you must be using an older compiler.

I have 8.3.0-6+rpi1.

That would explain it. Thank you!
