### ISSUE TITLE
Building crtbp_test.f90 under Mac OS X ver. 10.11.5 (El Capitan)

### ISSUE THREAD

**Issue by OrbitalMechanic** [jacobwilliams/Fortran-Astrodynamics-Toolkit#4]
I'm attempting to build and test the Fortran-Astrodynamics-Toolkit on a MacBook Pro under Mac OS X ver. 10.11.5. The problem I have at the moment is getting installation script, build.sh, to pick-up pyplot-fortran needed by crtbp_test.f90.

What do I need to do to get Fortran-Astrodynamics-Toolkit to include pyplot-fortran in its installation?

Sam Dupree.

**Comment by OrbitalMechanic** [comment]
As a footnote to my original submittal, I placed the files pyplot_module.mod and pyplot_module.o into the lib directory and attempted to rebuild the toolkit and test programs again. The report I got is contained in the attached file.

Hope this helps.
[fortran_astrodynamics_toolkit_report.txt](https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit/files/321546/fortran_astrodynamics_toolkit_report.txt)

**Comment by jacobwilliams** [comment]
You have to put the `pyplot_module.f90` in the `tests` directory, and then FoBiS will find it.

I need to set it up where the pyplot project is a git submodule of this one, but haven't gotten around to it yet.
