### ISSUE TITLE
Is there a more recent version of pyplot_fortran that includes add_contour and axis_equal?

### ISSUE THREAD

**Issue by OrbitalMechanic** [jacobwilliams/Fortran-Astrodynamics-Toolkit#5]
Is there a more recent version of pyplot_fortran that includes add_contour and axis_equal (see attached file) used in crtbp_test.f90?

[fortran_astrodynamics_toolkit_report.txt](https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit/files/321568/fortran_astrodynamics_toolkit_report.txt)

**Comment by jacobwilliams** [comment]
The [current one](https://github.com/jacobwilliams/pyplot-fortran/blob/master/src/pyplot_module.f90) has it.

**Comment by OrbitalMechanic** [comment]
Thanks that did the trick.

Sam Dupree.
