### ISSUE TITLE
Getting the Pork_Chop Test to Work

### ISSUE THREAD

**Issue by OrbitalMechanic** [jacobwilliams/Fortran-Astrodynamics-Toolkit#6]
I'm having trouble getting the pork_chop test to work. I can build the porkchop.so using f2py, but when I run the Python script pork_chop.py, I encounter an import problem involving porkchop as indicated in the attached file.

Please advise.

Sam Dupree.

[pork_chop_build_report.txt](https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit/files/321615/pork_chop_build_report.txt)

**Comment by jacobwilliams** [comment]
Hmmmm... I'm not even getting that far. My f2py won't even work:

``` bash
f2py -c porkchop.f90 -L../../lib/ -lfat -I../../lib/ -m porkchop only: generate_porkchop
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "porkchop" sources
f2py options: ['only:', 'generate_porkchop', ':']
f2py:> /var/folders/33/m9c933rd2k73nw_7f5gglxmm0000gn/T/tmp93Y95B/src.macosx-10.5-x86_64-2.7/porkchopmodule.c
creating /var/folders/33/m9c933rd2k73nw_7f5gglxmm0000gn/T/tmp93Y95B/src.macosx-10.5-x86_64-2.7
IOError: [Errno 2] No such file or directory: 'porkchop.f90'. Skipping file "porkchop.f90".
Reading fortran codes...
Post-processing...
Post-processing (stage 2)...
Building modules...
error: f2py target file '/var/folders/33/m9c933rd2k73nw_7f5gglxmm0000gn/T/tmp93Y95B/src.macosx-10.5-x86_64-2.7/porkchopmodule.c' not generated
```

I know it worked with whatever version of Python I was using at the time. I'll try to figure out what the problem is...

**Comment by OrbitalMechanic** [comment]
If it will help, I'm using the Anaconda distribution of Python 2.7.

Sam Dupree.

**Comment by jacobwilliams** [comment]
OK, I was in the wrong directory when getting the error above. Now I get the same error you do. Will look into it...

I'm also using Anaconda w/ Python 2.7.10.

**Comment by jacobwilliams** [comment]
I just committed the fix. It looks like I never updated this example when I refactored the ephemeris module. It should work now.

**Comment by OrbitalMechanic** [comment]
That fixed it. Thanks.

Sam Dupree.
