### ISSUE TITLE
Recommendation - ODE solvers moved to a separate package/module/class

### ISSUE THREAD

**Issue by cbcoutinho** [jacobwilliams/Fortran-Astrodynamics-Toolkit#7]
Howdy @jacobwilliams,

I'm really learning a lot from how you design your Fortran projects, and thinking about porting my projects to be more inline with this modern modular Fortran approach to programming.

You've done a bunch of work on including ode solvers into your code - I think this could be hugely beneficial to others that need an ode solver, but don't necessarily want to clone your astrodynamics toolkit to use them.

After a quick search, the only open-source options I know of that are currently available are either older (77 and/or 90), or are for teaching purposes and don't have the kind of safeguards in place for rigorous use - I am probably missing some great libraries, but the two I found that are otherwise _de facto_ standards are:

Codes available from FSU (John Burkardt):
https://people.sc.fsu.edu/~jburkardt/f_src/rkf45/rkf45.html

ODEPACK available from netlib:
http://www.netlib.org/odepack/

What do you think? Is there something tailored for modern fortran that meets this demand that I may have missed?

**Comment by cbcoutinho** [comment]
A bit more of searching came up with Fortran-FOSS-Programmers/FOODIE - it looks like they are trying to work on exactly what I'm looking for.

You can close this issue if you want

**Comment by szaghi** [comment]
@cbcoutinho Dear Chris, FOODIE adopts an Abstract Calculus Pattern while the Jacob approach is more _concrete_. Depending on your needs, one approach could be more suited than the other. I like to suggest you to study both, in particular I find very helpful study the code of Jacob, and then give a try to the one you feel is more suited for you. At the end, If you need help to _modularize_ the Jacob's solvers we can try to help.

> Do you like to join our Fortran FOSS group here on github? You are more than welcome.

My best regards.

**Comment by jacobwilliams** [comment]
Note: There's also [DDEABM](https://github.com/jacobwilliams/ddeabm) and [DOP853](https://github.com/jacobwilliams/dop853) which are separate projects.
