### ISSUE TITLE
lambert_module.f90

### ISSUE THREAD

**Issue by Virginia116** [jacobwilliams/Fortran-Astrodynamics-Toolkit#9]
Hello jacob,

I would like to ask you about this program for Gooding, Izzo and Arora. I have translated the programs to C because I don´t know Fortran. I have some doubts:
1) If I understand, nrev=0 (Arora) or multi_rev=0 (Gooding or Izzo) means that the orbit can be not only elliptic but hyperbolic or parabolic too. If they have value larger tan 0: 1, 2, ..we are considering elliptic orbits. How do you play with the parameters: long_way (defined in the 3 methods) and shortperiod (in Arora)? If for example the approach is defined by default for prograde orbits, in principle the time of flight (a priori data) defines  the orbit we are looking for and the radiovectors the transfer angle (smaller or larger than pi). In these programs ''long_way'' defines directly if the transfer is larger than pi. How do you identify prograde or retrograde transfer? What do you mean with shortperiod in Arora? You write ''for multirev I think...'' but it is not very clear for me.

2) I run in the 3 approaches the same example: r1=(20000,20000,0)km ; r2=(-20000,10000;0)km ; tof=86400sec ; longway=1; and then I change multi_revs or nrev from 0 to 2. Could you tell me what do you obtain when you select multi_revs=0 (or nrev=0)? I obtain close values but not the same for the 3 methods and I'm not sure if I have done something wrong. I also check the effect to change from shortperiod=true to shortperiod=false. The values are the same when nrev=0, but they change when nrev>0.

3) In the case of Gooding and Izzo when I select multi_revs=1 I obtain 3 results for v1 and v2 and when I select multi_revs=2 I obtain 5 results...but we cannot obtain more results tan the number of revolutions (one per #revolutions ) isn't it? In the case of Arora I obtain just one refers to the value provided by nrev.

Thank you in advance and thank you for providing all these programs to the community.

**Comment by jacobwilliams** [comment]
[This diagram](http://degenerateconic.com/lamberts-problem/) might help you (which is generated by the lambert test example). The multi-rev (nrev>0) cases can have two solutions (these are the shortperiod and longperiod from the Arora routine). See also the references cited in the code for more info on Lambert's problem.  

The interfaces to Gooding and Izzo are the same (they return all solutions for 0,1,...,nrev).  So, for nrev=1, you can get 3 solutions (1 for nrev=0 and 2 for nrev=1). The Arora one will only return the one you ask for (nrev=1, either shortperiod or longperiod).

The differences between the methods should be very small (1e-10 or less). If you run the (Fortran) test cases, there are some numerical comparisons.

**Comment by jacobwilliams** [comment]
FYI: see the `tests/lambert/lambert_test.f90` file for an example of how to call each one.

**Comment by Virginia116** [comment]
Thank you for the message. Now I understand the equivalence between de different methods (Gooding and Izzo wrt Arora). Just one question. When I see the diagram, if I consider the angular momentum given by r1xr2, it is positive and with the direction of (0,0,1). In that sense, If I see for example the red line, from r1 to r2, considering the sense of the angular momentum, by applying a counter-clockwise transfer (prograde transfer), we have a transfer angle smaller than pi and of course this is a shortway (<pi). If we see now the dotted red line, the longway (>pi) means that you go from r1 to r2 by applying a clockwise transfer (retrograde transfer)?  This is the only way I see to obtain a transfer angle larger than pi.

Thank you

**Comment by jacobwilliams** [comment]
The solid red curve from r1 to r2 passes r2, goes out to apoapsis, comes back (passing through r1 again), and then arrives at r2. It's "short way" because it starts heading in the <pi direction (CCW in this case). But notice that it is an `n=1` solution so it takes more than 1 rev to get there in the specified `dt`.

Similarly, the dashed red one goes CW ("long way" direction), passes r2, then r1 again, and then arrives at r2.

**Comment by Virginia116** [comment]
Everything clear. Thank you
